Add a way to run operations by name
We'll be adding more operations to this script and it will be easier if
we can just run these using their name from the cmdline.

diff --git a/bin/aws-account-setup b/bin/aws-account-setup
--- a/bin/aws-account-setup
+++ b/bin/aws-account-setup
@@ -19,29 +19,62 @@ create_analyzer() {
     fi
 }
 
-# Analyzer names and types based on the convention
-unused_analyzer_name="UnusedAccess-ConsoleAnalyzer-eu-west-2"
-unused_analyzer_type="ACCOUNT_UNUSED_ACCESS"
-external_analyzer_name="ExternalAccess-ConsoleAnalyzer-eu-west-2"
-external_analyzer_type="ACCOUNT"
+_op_create_unused_access_console_analyzer() {
+    # Create or verify Unused Access Analyzer
+    create_analyzer "UnusedAccess-ConsoleAnalyzer-eu-west-2" "ACCOUNT_UNUSED_ACCESS"
+}
 
-# Create or verify Unused Access Analyzer
-create_analyzer "$unused_analyzer_name" "$unused_analyzer_type"
+_op_create_external_access_console_analyzer() {
+    # Create or verify External Access Analyzer
+    create_analyzer "ExternalAccess-ConsoleAnalyzer-eu-west-2" "ACCOUNT"
+}
 
-# Create or verify External Access Analyzer
-create_analyzer "$external_analyzer_name" "$external_analyzer_type"
+_op_enable_db_delete_protection() {
+    # Find the RDS instances and store them in a varibale to be used later
+    db_clusters=$(aws rds describe-db-clusters --output yaml | grep -E 'DBClusterIdentifier\W+' | awk '{print $2}')
 
-# Find the RDS instances and store them in a varibale to be used later
-db_clusters=$(aws rds describe-db-clusters --output yaml | grep -E 'DBClusterIdentifier\W+' | awk '{print $2}')
+    # Loop through each instance and enable deletion protection
+    for db_cluster in $db_clusters; do
+        echo "Enabling deletion protection for cluster $db_cluster"
+        aws rds modify-db-cluster \
+            --db-cluster-identifier $db_cluster \
+            --deletion-protection \
+            --apply-immediately \
+            --no-cli-pager
+    done
+}
 
-# Loop through each instance and enable deletion protection
-for db_cluster in $db_clusters; do
-    echo "Enabling deletion protection for cluster $db_cluster"
-    aws rds modify-db-cluster \
-        --db-cluster-identifier $db_cluster \
-        --deletion-protection \
-        --apply-immediately \
-        --no-cli-pager
+print_operations() {
+    echo "Available operations:"
+    declare -F | awk '/_op_/ {sub(/.*_op_/, "  "); print}'
+}
+
+while getopts ":h" opt; do
+    case ${opt} in
+        h )
+            echo "Usage: $0 [operation [operation]] ..."
+            echo ""
+            print_operations
+            exit 0
+            ;;
+        \? )
+            echo "Invalid Option: -$OPTARG" 1>&2
+            exit 1
+            ;;
+    esac
+
+    echo $0
 done
 
-echo "Script finish executing."
+while [[ -n "$1" ]]; do
+    if declare -f "_op_$1" > /dev/null; then
+        echo "Running operation $1"
+        "_op_$1"
+    else
+        echo "Operation $1 does not exist."
+        echo ""
+        print_operations
+    fi
+    shift
+done
+
