Add check for successful data replication deployment

diff --git a/.github/workflows/data-replication-pipeline.yml b/.github/workflows/data-replication-pipeline.yml
--- a/.github/workflows/data-replication-pipeline.yml
+++ b/.github/workflows/data-replication-pipeline.yml
@@ -1,5 +1,5 @@
 name: Deploy data replication
-run-name: Deploy data replication to ${{ inputs.environment }}
+run-name: Deploy data replication from ${{ inputs.git_ref_to_deploy || github.ref_name }} to ${{ inputs.environment }}
 
 on:
   workflow_dispatch:
@@ -187,6 +187,7 @@ jobs:
           family_name="mavis-data-replication-task-definition-$environment"
           echo "$(jq --arg f "$family_name" '.family = $f' "$file_path")" > "$file_path"
       - name: Deploy data-replication service
+        id: ecs-deploy
         uses: aws-actions/amazon-ecs-deploy-task-definition@v2
         with:
           task-definition: ${{ runner.temp }}/data-replication-task-definition.json
@@ -194,3 +195,13 @@ jobs:
           service: mavis-${{ inputs.environment }}-data-replication
           force-new-deployment: true
           wait-for-service-stability: true
+      - name: Check if deployment was successful
+        run: |
+          current_task_definition_arn=$(aws ecs describe-services --cluster mavis-$environment-data-replication --services mavis-$environment-data-replication --query services[0].deployments[0].taskDefinition | jq -r ".")
+          new_task_definition_arn=${{ steps.ecs-deploy.outputs.task-definition-arn }}
+          echo "Current task definition arn: $current_task_definition_arn"
+          echo "Expected task definition arn after deployment: $new_task_definition_arn"
+          if [ "$current_task_definition_arn" != "$new_task_definition_arn" ]; then
+            echo "Task definition arns don't match, likely due to a rollback to the previous version. Deployment failed."
+            exit 1
+          fi
