Validate inputs for deploy.yml workflow
* This change lets the workflow fail early if the `git_ref_to_deploy` input is not provided. Even though this input is required only for production, the check is also added for preview to make sure that the workflows are similar for both environments

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -44,9 +44,22 @@ on:
         default: all
 
 jobs:
+  validate-inputs:
+    runs-on: ubuntu-latest
+    permissions: {}
+    steps:
+      - name: Validate inputs
+        run: |
+          if [[ "${{ inputs.environment }}" == "preview" || "${{ inputs.environment }}" == "production" ]]; then
+            if [[ -z "${{ inputs.git_ref_to_deploy }}" ]]; then
+              echo "Error: git_ref_to_deploy is required for preview and production environments."
+              exit 1
+            fi
+          fi
   determine-git-sha:
     runs-on: ubuntu-latest
     permissions: {}
+    needs: validate-inputs
     outputs:
       git-sha: ${{ steps.get-git-sha.outputs.git-sha }}
     steps:
